//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tello_Interface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StretchImage")]
        public global::System.Windows.Forms.PictureBoxSizeMode Strech {
            get {
                return ((global::System.Windows.Forms.PictureBoxSizeMode)(this["Strech"]));
            }
            set {
                this["Strech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StretchImage")]
        public global::System.Windows.Forms.PictureBoxSizeMode theone {
            get {
                return ((global::System.Windows.Forms.PictureBoxSizeMode)(this["theone"]));
            }
            set {
                this["theone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoSize")]
        public global::System.Windows.Forms.PictureBoxSizeMode sizes {
            get {
                return ((global::System.Windows.Forms.PictureBoxSizeMode)(this["sizes"]));
            }
            set {
                this["sizes"] = value;
            }
        }
    }
}
